service: typescript-sls
provider:
  name: aws
  runtime: nodejs10.x
plugins:
  - serverless-iam-roles-per-function
  - serverless-cf-vars
  - serverless-plugin-typescript
functions:
  tsFunction:
    handler: index.handler
    description:
      Fn::Sub:
        - 'Stack #{StackTagName} Environment #{EnvironmentTagName} Function #{ResourceName}'
        - ResourceName: tsFunction
    runtime: nodejs10.x
    tracing: Active
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          - xray:GetSamplingRules
          - xray:GetSamplingTargets
          - xray:GetSamplingStatisticSummaries
        Resource: '*'
    tags:
      runtimeOption: typescript
  normalFunction:
    handler: index.handler
    description:
      Fn::Sub:
        - 'Stack #{StackTagName} Environment #{EnvironmentTagName} Function #{ResourceName}'
        - ResourceName: normalFunction
    runtime: nodejs10.x
    tracing: Active
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          - xray:GetSamplingRules
          - xray:GetSamplingTargets
          - xray:GetSamplingStatisticSummaries
        Resource: '*'
  anotherTsFunction:
    handler: index.handler
    description:
      Fn::Sub:
        - 'Stack #{StackTagName} Environment #{EnvironmentTagName} Function #{ResourceName}'
        - ResourceName: anotherTsFunction
    runtime: nodejs10.x
    tracing: Active
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          - xray:GetSamplingRules
          - xray:GetSamplingTargets
          - xray:GetSamplingStatisticSummaries
        Resource: '*'
    tags:
      runtimeOption: typescript
  moreTs:
    handler: index.handler
    description:
      Fn::Sub:
        - 'Stack #{StackTagName} Environment #{EnvironmentTagName} Function #{ResourceName}'
        - ResourceName: moreTs
    runtime: nodejs10.x
    tracing: Active
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          - xray:GetSamplingRules
          - xray:GetSamplingTargets
          - xray:GetSamplingStatisticSummaries
        Resource: '*'
    tags:
      runtimeOption: typescript
    memorySize: 3008
    timeout: 1
resources:
  Parameters:
    StackTagName:
      Type: String
      Description: Stack Name (injected by Stackery at deployment time)
      Default: typescript-sls
    EnvironmentTagName:
      Type: String
      Description: Environment Name (injected by Stackery at deployment time)
      Default: dev