service: typescript-sls
provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - xray:GetSamplingRules
        - xray:GetSamplingTargets
        - xray:GetSamplingStatisticSummaries
      Resource: '*'
plugins:
  - serverless-iam-roles-per-function
  - serverless-cf-vars
  - serverless-iam-roles-per-function
  - serverless-iam-roles-per-function